CREATE TABLE IF NOT EXISTS ACCOUNTS(
    ACCOUNT_ID              INT NOT NULL,
    ACCOUNT_NAME            VARCHAR(64) NOT NULL UNIQUE,
    ACCOUNT_PASSWORD        VARCHAR(64) NOT NULL,
    ENABLED                 BOOLEAN NOT NULL DEFAULT TRUE
);
CREATE SEQUENCE SEQ_ACCOUNTS START 100;
ALTER TABLE ACCOUNTS ADD CONSTRAINT ACCOUNT_ID PRIMARY KEY (ACCOUNT_ID);


CREATE TABLE IF NOT EXISTS AUTHORITIES(
    AUTHORITY_ID            INT NOT NULL,
    ACCOUNT_ID              INT NOT NULL,
    AUTHORITY               VARCHAR(32) NOT NULL
);
CREATE SEQUENCE SEQ_AUTHORITIES START 100;
ALTER TABLE AUTHORITIES ADD CONSTRAINT AUTHORITY_ID PRIMARY KEY (AUTHORITY_ID);
ALTER TABLE AUTHORITIES ADD CONSTRAINT FK_ACCOUNTS_ACCOUNT_ID FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID);
ALTER TABLE AUTHORITIES ADD CONSTRAINT UQ_ACCOUNT_ID_AUTHORITY UNIQUE (ACCOUNT_ID, AUTHORITY);