CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID              INT NOT NULL,
    ACCOUNT_NAME            VARCHAR(50) NOT NULL,
    ACCOUNT_PASSWORD        VARCHAR(50) NOT NULL,
    VERSION                 INTEGER     NOT NULL,
    CREATED_BY              VARCHAR(50) NOT NULL,
    CREATED_DATE            TIMESTAMP   NOT NULL,
    UPDATED_BY              VARCHAR(50) NOT NULL,
    UPDATED_DATE            TIMESTAMP   NOT NULL
);

CREATE SEQUENCE SEQ_ACCOUNT START 1;
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_ID PRIMARY KEY (ID);