CREATE TABLE IF NOT EXISTS ACCOUNT(
    ID              INT NOT NULL,
    ACCOUNT_NAME            VARCHAR(50) NOT NULL,
    ACCOUNT_PASSWORD        VARCHAR(50) NOT NULL
);

CREATE SEQUENCE SEQ_ACCOUNT START 1;
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCOUNT_ID PRIMARY KEY (ID);