CREATE TABLE IF NOT EXISTS ACCOUNT_DETAILS(
    ACCOUNT_DETAIL_ID       INT NOT NULL,
    PHONE                   VARCHAR(16),
    ADDRESS                 VARCHAR(256),
    NATIONALITY             VARCHAR(2)
);
CREATE SEQUENCE SEQ_ACCOUNT_DETAILS START 100;
ALTER TABLE ACCOUNT_DETAILS ADD CONSTRAINT ACCOUNT_DETAIL_ID PRIMARY KEY (ACCOUNT_DETAIL_ID);

ALTER TABLE ACCOUNTS ADD COLUMN ACCOUNT_DETAIL_ID INT;
ALTER TABLE ACCOUNTS ADD CONSTRAINT FK_ACCOUNT_DETAILS_ACCOUNT_DETAIL_ID FOREIGN KEY (ACCOUNT_DETAIL_ID) REFERENCES ACCOUNT_DETAILS (ACCOUNT_DETAIL_ID);
